include { PREDICT_MULTI_MOUSE_SEGMENTATION; PREDICT_MULTI_MOUSE_KEYPOINTS; PREDICT_MULTI_MOUSE_IDENTITY; GENERATE_MULTI_MOUSE_TRACKLETS } from "${projectDir}/nextflow/modules/multi_mouse"
include { VIDEO_TO_POSE } from "${projectDir}/nextflow/modules/utils"

workflow MULTI_MOUSE_TRACKING {
    take:
    input_video
    num_animals

    main:
    VIDEO_TO_POSE(input_video)
    PREDICT_MULTI_MOUSE_SEGMENTATION(VIDEO_TO_POSE.out)
    PREDICT_MULTI_MOUSE_KEYPOINTS(PREDICT_MULTI_MOUSE_SEGMENTATION.out)
    PREDICT_MULTI_MOUSE_IDENTITY(PREDICT_MULTI_MOUSE_KEYPOINTS.out)
    GENERATE_MULTI_MOUSE_TRACKLETS(PREDICT_MULTI_MOUSE_IDENTITY.out, num_animals)
}
