[tool.poetry]
name = "mouse-tracking-runtime"
version = "0.1.0"
description = ""
authors = ["Brian Geuther <Brian.Geuther@jax.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
